import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {trace,makeDesign} from './geometry.js';
import {make3mf,makeSTLs} from './export.js';
const $=id=>document.getElementById(id),viewport=$('viewport');
let artwork=null,design=null,timer,renderer,scene,camera,controls,group,view='perspective';
function initScene(){renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);viewport.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive 3D preview of your keychain');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(35,1,.1,2000);camera.up.set(0,0,1);camera.position.set(15,-80,115);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=25;controls.maxDistance=400;scene.add(new THREE.HemisphereLight(0xffffff,0x4c5b84,2.8));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-40,-40,100);scene.add(light);const fill=new THREE.DirectionalLight(0xc8d9ff,1);fill.position.set(40,70,30);scene.add(fill);new ResizeObserver(()=>{renderer.setSize(viewport.clientWidth,viewport.clientHeight);camera.aspect=viewport.clientWidth/viewport.clientHeight;camera.updateProjectionMatrix();}).observe(viewport);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});}
function readOptions(){return {width:+$('width').value,border:+$('border').value,base:+$('base').value,relief:+$('relief').value,hole:+$('hole').value,imageSize:+$('image-size').value,placement:$('placement').value,colors:[$('backing-color').value,$('name-color').value,$('image-color').value]};}
function namePaths(){const text=$('name').value.trim();if(!text)return[];const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),fonts={rounded:'900 150px Arial, sans-serif',classic:'bold 150px Georgia, serif',mono:'bold 150px "Courier New", monospace'};ctx.font=fonts[$('font').value];const m=ctx.measureText(text);canvas.width=Math.ceil(m.width)+40;canvas.height=220;ctx.font=fonts[$('font').value];ctx.fillStyle='#000';ctx.textBaseline='alphabetic';ctx.fillText(text,20,165);return trace(ctx.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height,180);}
function imagePaths(){if(!artwork)return[];const canvas=document.createElement('canvas'),ratio=Math.min(1,400/Math.max(artwork.width,artwork.height));canvas.width=Math.max(1,Math.round(artwork.width*ratio));canvas.height=Math.max(1,Math.round(artwork.height*ratio));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(artwork,0,0,canvas.width,canvas.height);const result=trace(ctx.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height,+$('threshold').value,$('invert').checked);if(!result.length)throw Error('No image details found. Adjust the threshold or use light details.');return result;}
function dispose(){if(group){scene.remove(group);for(const mesh of group.children){mesh.geometry.dispose();mesh.material.dispose();}}}
function fit(){if(!design)return;const extent=Math.max(design.bounds.width/(camera.aspect||1),design.bounds.height,40),dist=extent*1.85;camera.position.set(view==='top'?0:dist*.12,view==='top'?.001:-dist*.55,dist);controls.target.set(0,0,0);controls.update();}
function update(){clearTimeout(timer);$('export').disabled=$('stl').disabled=true;try{if(!$('design-form').checkValidity())throw Error('Use the indicated range for backing and detail thickness.');const o=readOptions();const next=makeDesign(namePaths(),imagePaths(),o);dispose();design=next;group=new THREE.Group();for(const p of design.parts){const mesh=new THREE.Mesh(p.geometry,new THREE.MeshStandardMaterial({color:p.color,roughness:.42,metalness:.04}));mesh.name=p.name;group.add(mesh);}scene.add(group);fit();$('loading').hidden=true;$('dimensions').textContent=`${design.bounds.width.toFixed(1)} × ${design.bounds.height.toFixed(1)} × ${design.height.toFixed(1)} mm`;$('status').textContent=`${design.parts.length} aligned parts · millimeters · flat backing`;$('export').disabled=$('stl').disabled=false;$('image-part-note').textContent=artwork?'Raised silhouette':'Add artwork to include';}catch(e){$('status').textContent=e.message;$('loading').hidden=false;$('loading').textContent='Adjust your design to continue';}}
function schedule(){for(const id of ['width','border','hole','image-size','threshold'])$(id+'-out').textContent=$(id).value+(id==='threshold'?'':' mm');$('export').disabled=$('stl').disabled=true;$('status').textContent='Updating your model…';clearTimeout(timer);timer=setTimeout(update,200);}
function download(data,extension,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=($('name').value.trim().replace(/[^a-z0-9-]/gi,'_')||'keychain')+extension;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('design-form').addEventListener('submit',e=>e.preventDefault());$('design-form').addEventListener('input',e=>{if(e.target.id!=='upload')schedule();});
for(const id of ['backing-color','name-color','image-color'])$(id).addEventListener('input',()=>{if(!design)return;const colors=readOptions().colors;for(const p of design.parts){p.color=colors[['Backing','Name','Image'].indexOf(p.name)];group.getObjectByName(p.name).material.color.set(p.color);}});
let uploadVersion=0;
$('upload').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const token=++uploadVersion;let url;try{if(file.size>5*1024*1024)throw Error('Choose an image smaller than 5 MB.');if(!/\.(svg|png|jpe?g)$/i.test(file.name))throw Error('Choose an SVG, PNG or JPG image.');let blob=file;if(/\.svg$/i.test(file.name)){const source=await file.text(),doc=new DOMParser().parseFromString(source,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='svg')throw Error('This SVG could not be read.');if(doc.querySelector('script,foreignObject,image,use')||/url\s*\(|@import|(?:href)\s*=/i.test(source))throw Error('Use a self-contained SVG made of paths, without linked images, fonts, or symbols.');blob=new Blob([source],{type:'image/svg+xml'});}url=URL.createObjectURL(blob);const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('This image could not be read. Try a PNG or a simple SVG.'));img.src=url;});if(token!==uploadVersion)return;if(!img.width||!img.height||img.width*img.height>50000000)throw Error('Image dimensions are too large. Resize to under 50 megapixels.');artwork=img;$('image-label').textContent=file.name;$('image-controls').hidden=false;$('remove').hidden=false;update();}catch(err){$('status').textContent=err.message;}finally{if(url)URL.revokeObjectURL(url);}});
$('remove').addEventListener('click',()=>{uploadVersion++;artwork=null;$('upload').value='';$('image-label').textContent='No image added';$('image-controls').hidden=true;$('remove').hidden=true;update();});
for(const id of ['perspective','top'])$(id).addEventListener('click',()=>{view=id;$('perspective').classList.toggle('active',id==='perspective');$('top').classList.toggle('active',id==='top');fit();});
$('export').addEventListener('click',()=>{if(design)download(make3mf(design,($('name').value.trim()||'Custom')+' keychain'),'.3mf','model/3mf');});$('stl').addEventListener('click',()=>{if(design)download(makeSTLs(design),'-parts.zip','application/zip');});
try{initScene();update();}catch(e){$('loading').textContent='3D preview needs WebGL. Please enable hardware acceleration or use another browser.';$('status').textContent=e.message;}
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'configure_keychain',title:'Configure keychain',description:'Set the keychain name and design width, then rebuild the visible printable model.',inputSchema:{type:'object',properties:{name:{type:'string',maxLength:24},width:{type:'number',minimum:35,maximum:110}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['name','width'].includes(k))||(input.name!==undefined&&(typeof input.name!=='string'||input.name.length>24))||(input.width!==undefined&&(!Number.isFinite(input.width)||input.width<35||input.width>110)))throw Error('Invalid name or width.');if(input.name!==undefined)$('name').value=input.name;if(input.width!==undefined){$('width').value=input.width;$('width-out').textContent=input.width+' mm';}update();return{status:$('status').textContent,parts:design?.parts.map(p=>p.name),exportReady:!$('export').disabled};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
