import {zipSync,strToU8} from './vendor/fflate.js';
import {indexedMesh} from './geometry.js';
const xml=s=>s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
export function make3mf(design,title){const objects=design.parts.map((p,i)=>{const m=indexedMesh(p.geometry);return `<object id="${i+1}" type="model" name="${p.name}" pid="10" pindex="${i}"><mesh><vertices>${m.vertices.map(v=>`<vertex x="${v[0]}" y="${v[1]}" z="${v[2]}"/>`).join('')}</vertices><triangles>${m.triangles.map(t=>`<triangle v1="${t[0]}" v2="${t[1]}" v3="${t[2]}"/>`).join('')}</triangles></mesh></object>`;}).join('');
 const model=`<?xml version="1.0" encoding="UTF-8"?><model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"><metadata name="Title">${xml(title)}</metadata><metadata name="Application">Keychain Studio</metadata><resources><basematerials id="10">${design.parts.map(p=>`<base name="${p.name}" displaycolor="${p.color.toUpperCase()}FF"/>`).join('')}</basematerials>${objects}<object id="20" type="model" name="${xml(title)}"><components>${design.parts.map((_,i)=>`<component objectid="${i+1}"/>`).join('')}</components></object></resources><build><item objectid="20"/></build></model>`;
 return zipSync({'[Content_Types].xml':strToU8('<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>'),'_rels/.rels':strToU8('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>'),'3D/3dmodel.model':strToU8(model)}, {level:6});
}
export function stlBytes(g){const p=g.getAttribute('position'),n=p.count/3,buffer=new ArrayBuffer(84+n*50),view=new DataView(buffer);view.setUint32(80,n,true);for(let t=0;t<n;t++){let at=84+t*50+12;for(let j=0;j<3;j++)for(let a=0;a<3;a++){view.setFloat32(at,p.array[(t*3+j)*3+a],true);at+=4;}}return new Uint8Array(buffer);}
export function makeSTLs(design){const files={'READ ME.txt':strToU8('Select all STL files together in Bambu Studio. Import as ONE object with multiple parts. All parts share the same origin in millimeters. Do not auto-arrange or drop individual parts onto the plate. Expand the object and assign a filament to Backing, Name, and Image. The 3MF download preserves this assembly automatically.')};for(const p of design.parts)files[p.name+'.stl']=stlBytes(p.geometry);return zipSync(files,{level:6});}
